'use strict';
const advancedCopy = {
  pt: {
    ...foundationCopy.pt,
    label:'SQL avançado · Para quem já conhece os fundamentos',
    title:'Advanced SQL with Oracle', subtitle:'A Practical Guide',
    tagline:'Consultas mais complexas.<br>Resultados <em>que você consegue explicar.</em>',
    intro:'Avance além do SQL básico com CTEs, funções analíticas, hierarquias e sincronização de dados. Aprenda a validar os resultados e investigar a execução das consultas, sem confundir sintaxe mais elaborada com melhor performance.',
    summary:'Aprofunde suas consultas Oracle com CTEs, funções analíticas, rankings, MERGE e planos de execução. Exemplos, exercícios comentados e um projeto de conciliação de vendas e pagamentos.',
    view:'Conhecer o e-book', validation:'Comprar na Payhip',
    validationNote:'A compra é realizada na Payhip. Consulte o preço e as condições na página do produto.',
    cover:'assets/advanced-sql-oracle-cover-v2.png',
    purchaseUrl:'https://payhip.com/b/YsMiQ',
    coverAlt:'Capa de Advanced SQL with Oracle: A Practical Guide, de Vitor Tee How Siao Júnior',
    level:'Requer conhecimento de SQL básico',
    stats:[['44','páginas'],['26','seções'],['10','exercícios'],['30','dias no plano de estudo']],
    learnTitle:'Da consulta correta à análise da execução.',
    learnIntro:'O guia usa Oracle Database 19c como referência. A progressão conecta organização de consultas, cálculos analíticos, integração e investigação de performance.',
    modules:[
      ['Resultados confiáveis e CTEs','Granularidade do resultado, joins, subconsultas, WITH, CASE e medidas condicionais para evitar duplicidades e totais incorretos.'],
      ['Funções analíticas e rankings','OVER, PARTITION BY, ROW_NUMBER, RANK, DENSE_RANK, janelas, totais acumulados, LAG e LEAD.'],
      ['Agregação e transformação','GROUPING SETS, ROLLUP, CUBE, PIVOT e UNPIVOT para criar resumos e reorganizar informações.'],
      ['Hierarquias e períodos','CONNECT BY, consultas recursivas, tratamento de ciclos, calendários completos e padrões de gaps and islands.'],
      ['Sincronização com MERGE','Validação das chaves de origem, atualização e inserção de dados, transações, SAVEPOINT e ROLLBACK.'],
      ['Planos e reescrita com evidências','Planos estimados e estatísticas de execução, DBMS_XPLAN e comparação de consultas equivalentes antes de aceitar uma melhoria.']
    ],
    projectKicker:'Projeto final · Conciliação de vendas e pagamentos',
    projectTitle:'Vendas e pagamentos.<br>Totais sem duplicidade.',
    projectIntro:'Combine técnicas em um cenário de loja: concilie valores por pedido, construa indicadores mensais e sincronize metas com validação e controle de transação.',
    projectTasks:['Conciliar receita, pagamentos confirmados e saldo por pedido','Comparar receita mensal, crescimento, acumulado e metas','Montar o ranking dos produtos por categoria, definindo o tratamento de empates','Validar a carga de metas com MERGE e testar o rollback','Comparar duas consultas equivalentes com evidências de execução'],
    projectStages:[['ORDER TOTALS','Somar itens por pedido'],['CONFIRMED PAYMENTS','Somar pagamentos confirmados por pedido'],['RECONCILIATION','Conciliar receita, pagamentos e saldo']],
    projectNote:'Pratique em um schema isolado. Os exemplos não devem ser executados diretamente em produção; alguns diagnósticos exigem privilégios adicionais.',
    includedTitle:'Prática e revisão dentro do próprio guia.',
    included:['Schema de estudo e dados de exemplo','Exemplos SQL e verificações rápidas ao longo dos capítulos','Projeto final de conciliação de vendas e pagamentos','10 exercícios com gabarito comentado','Respostas de revisão dos capítulos','Plano de estudo de 30 dias, checklist, glossário e referências técnicas'],
    audienceTitle:'Para quem já escreve SQL e quer ir além.',
    audience:'Desenvolvedores, analistas e profissionais de suporte que precisam de relatórios confiáveis, rankings, comparação e sincronização de dados. É necessário conhecer SELECT, filtros, joins, GROUP BY, HAVING, subconsultas simples, UNION ALL e a finalidade de COMMIT e ROLLBACK. Não exige experiência prévia em programação PL/SQL.',
    faq:[
      ['O e-book está em português?','Não. Esta edição do PDF está em inglês. A landing page está disponível em português e inglês, mas isso não altera o idioma do livro.'],
      ['É indicado para iniciantes absolutos?','Não. O guia pressupõe SQL básico. Se você ainda está começando, conheça primeiro o Database Foundations.'],
      ['Qual versão do Oracle é usada?','A sintaxe principal usa Oracle Database 19c como referência. Você precisa de um ambiente de estudo isolado e um cliente SQL compatível com Oracle.'],
      ['Inclui videoaulas ou arquivos SQL separados?','É um e-book em PDF. O schema, os dados de exemplo, os exercícios e as respostas estão no próprio guia; não há promessa de videoaulas ou arquivos separados.'],
      ['O plano de 30 dias garante domínio do assunto?','Não. É uma sugestão de organização da prática, não uma garantia de aprendizado, emprego, certificação ou resultado de performance.'],
      ['Como compro?','O botão Comprar na Payhip abre a página do produto no link informado pelo autor. Confira preço e condições nessa página.']
    ],
    closing:'O próximo passo do seu SQL<br>começa com prática.',
    closingIntro:'Conheça o conteúdo e acesse a página do produto na Payhip para consultar as condições de compra.',
    meta:'Advanced SQL with Oracle: e-book em inglês com 44 páginas sobre CTEs, funções analíticas, MERGE e planos de execução, com exercícios e projeto de conciliação.'
  },
  en: {
    ...foundationCopy.en,
    label:'Advanced SQL · Beyond the foundations',
    title:'Advanced SQL with Oracle', subtitle:'A Practical Guide',
    tagline:'More demanding queries.<br>Results <em>you can explain.</em>',
    intro:'Move beyond basic SQL with CTEs, window functions, hierarchies and data synchronization. Learn to validate results and investigate query execution, without assuming that more elaborate syntax means better performance.',
    summary:'Develop your Oracle queries with CTEs, window functions, rankings, MERGE and execution plans. Includes examples, explained exercises and a sales and payment reconciliation project.',
    view:'Explore the e-book', validation:'Buy on Payhip',
    validationNote:'Purchasing takes place on Payhip. Check pricing and terms on the product page.',
    cover:'assets/advanced-sql-oracle-cover-v2.png',
    purchaseUrl:'https://payhip.com/b/YsMiQ',
    coverAlt:'Cover of Advanced SQL with Oracle: A Practical Guide, by Vitor Tee How Siao Júnior',
    level:'Basic SQL knowledge required',
    stats:[['44','pages'],['26','sections'],['10','exercises'],['30','days in the study plan']],
    learnTitle:'From correct results to execution analysis.',
    learnIntro:'The guide uses Oracle Database 19c as its baseline. Its progression connects query organization, analytical calculations, integration and performance investigation.',
    modules:[
      ['Reliable results and CTEs','Result grain, joins, subqueries, WITH, CASE and conditional measures to prevent duplicated rows and incorrect totals.'],
      ['Window functions and rankings','OVER, PARTITION BY, ROW_NUMBER, RANK, DENSE_RANK, window frames, running totals, LAG and LEAD.'],
      ['Aggregation and reshaping','GROUPING SETS, ROLLUP, CUBE, PIVOT and UNPIVOT for summaries and data reshaping.'],
      ['Hierarchies and periods','CONNECT BY, recursive queries, cycle handling, complete calendars, and gaps and islands patterns.'],
      ['Synchronization with MERGE','Source key validation, updates and inserts, transactions, SAVEPOINT and ROLLBACK.'],
      ['Plans and evidence-based rewrites','Estimated plans and runtime statistics, DBMS_XPLAN, and equivalent-query comparisons before accepting an improvement.']
    ],
    projectKicker:'Final project · Sales and payment reconciliation',
    projectTitle:'Sales and payments.<br>Totals without duplication.',
    projectIntro:'Combine techniques in a store scenario: reconcile order amounts, build monthly indicators and synchronize targets with validation and transaction control.',
    projectTasks:['Reconcile revenue, confirmed payments and balance per order','Compare monthly revenue, growth, running totals and targets','Rank products within each category with an explicit tie policy','Validate a MERGE target load and test rollback','Compare two equivalent queries using execution evidence'],
    projectStages:[['ORDER TOTALS','Summarize order items per order'],['CONFIRMED PAYMENTS','Summarize confirmed payments per order'],['RECONCILIATION','Compare revenue, payments and balances']],
    projectNote:'Practice in an isolated study schema. Do not run examples directly against production data; some diagnostics require additional privileges.',
    includedTitle:'Practice and review within the guide.',
    included:['Study schema and sample data','SQL examples and Quick Checks throughout the chapters','Final sales and payment reconciliation project','10 exercises with a commented answer key','Chapter review answers','30-day study plan, checklist, glossary and technical references'],
    audienceTitle:'For SQL users ready to go further.',
    audience:'Developers, analysts and support professionals who need reliable reports, rankings, data comparison and synchronization. You should know SELECT, filters, joins, GROUP BY, HAVING, simple subqueries, UNION ALL and the purpose of COMMIT and ROLLBACK. Prior PL/SQL programming experience is not required.',
    faq:[
      ['Is the e-book in Portuguese?','No. This PDF edition is in English. The landing page is available in Portuguese and English, but that does not change the book’s language.'],
      ['Is it for complete beginners?','No. The guide assumes basic SQL knowledge. If you are just getting started, explore Database Foundations first.'],
      ['Which Oracle version is used?','The core syntax targets Oracle Database 19c. You need an isolated study environment and an Oracle-compatible SQL client.'],
      ['Are video lessons or separate SQL files included?','This is a PDF e-book. Schema setup, sample data, exercises and explained answers are within the guide; video lessons or separate files are not promised.'],
      ['Does the 30-day plan guarantee mastery?','No. It is a suggested practice schedule, not a guarantee of learning, employment, certification or performance results.'],
      ['How do I purchase it?','The Buy on Payhip button opens the product page using the link supplied by the author. Check pricing and terms there.']
    ],
    closing:'Your next SQL step<br>starts with practice.',
    closingIntro:'Explore the contents and visit the Payhip product page to check purchase terms.',
    meta:'Advanced SQL with Oracle: a 44-page English e-book on CTEs, window functions, MERGE and execution plans, with exercises and a reconciliation project.'
  }
};
function advancedLanding(c) { return ebookLanding(advancedCopy[state.language],c); }
