'use strict';
const EMAIL = 'vitor.teehow@gmail.com';
const POLICY = 'https://teehow.github.io/controle-financeiro-app/';
const pages = ['home', 'services', 'courses', 'app', 'contact', 'databases', 'sql', 'plsql', 'bundle'];
const copy = {
  pt: {
    locale:'pt-BR', suffix:'Consultoria em Tecnologia', skip:'Pular para o conteúdo', menu:'Menu', close:'Fechar menu', change:'Switch to English', nav:['Início','Serviços','Cursos e e-books','Fatura na Risca','Contato'],
    title:'Tecnologia com propósito.', eyebrow:'Tee How · Consultoria em Tecnologia', hero:'Ideias claras.<br>Soluções <em>que fazem sentido.</em>', intro:'Consultoria, soluções digitais e aprendizado prático. Transformamos necessidades em ferramentas úteis, com clareza, organização e atenção a quem vai utilizá-las.',
    talk:'Vamos conversar', explore:'Conheça nosso trabalho', sideLabel:'CLAREZA / PRÁTICA / EVOLUÇÃO', side:'Do problema real<br>à solução <strong>digital.</strong>', topics:['Consultoria','Aplicativos','Automação','Banco de dados'],
    servicesKicker:'Consultoria em banco de dados', servicesTitle:'Dados bem cuidados.<br>Operações mais eficientes.', servicesIntro:'Da performance das consultas à organização dos dados: soluções para tornar seu ambiente mais confiável, eficiente e preparado para evoluir.', servicesPage:'Serviços em banco de dados', servicesMore:'Conheça todas as áreas', processTitle:'Como trabalhamos', processIntro:'O escopo é definido a partir do seu ambiente, das prioridades do negócio e dos riscos de cada alteração.', processSteps:[['Diagnóstico','Entendemos o ambiente, identificamos gargalos e alinhamos as prioridades.'],['Plano de ação','Definimos o escopo, as recomendações e os critérios de validação antes de executar.'],['Execução e validação','Aplicamos as mudanças acordadas, verificamos os resultados e documentamos as entregas.']],
    services:[
      ['Performance e tuning','Identificação de gargalos e otimização de consultas e rotinas para aproveitar melhor os recursos do ambiente.',['Análise de consultas e planos de execução','Revisão de índices e estatísticas','Diagnóstico de lentidão, bloqueios e consumo de recursos']],
      ['Administração de bancos de dados','Organização das rotinas de operação e manutenção, com atenção à estabilidade, segurança e continuidade.',['Configuração, manutenção e monitoramento','Revisão de acessos e privilégios','Planejamento de backup e testes de recuperação']],
      ['Modelagem e arquitetura de dados','Estruturas de dados alinhadas às regras do negócio, com consistência e espaço para evolução.',['Modelagem lógica e física','Revisão de tabelas, chaves e relacionamentos','Integridade, padronização e documentação']],
      ['Desenvolvimento SQL e PL/SQL','Consultas e rotinas de banco de dados organizadas para apoiar aplicações e processos do negócio.',['Consultas SQL e regras de negócio','Procedures, functions e packages','Revisão de código e automação de rotinas']],
      ['Integração, migração e qualidade','Apoio à movimentação e integração de dados, com validações para preservar a consistência das informações.',['Mapeamento e transformação de dados','Planejamento de cargas e migrações','Conciliação, tratamento de duplicidades e validação']],
      ['Dados para análise e relatórios','Preparação de informações para facilitar a leitura de indicadores e apoiar decisões com dados consistentes.',['Consultas e bases para relatórios','Definição e validação de indicadores','Organização de dados para dashboards e análises']]
    ],
    productKicker:'Nosso aplicativo', productTitle:'Menos surpresa.<br>Mais controle.', appTagline:'Seus cartões sob controle', appIntro:'O Fatura na Risca reúne recursos para acompanhar compras, organizar faturas e planejar os próximos meses no Android.', appStatus:'Em preparação para publicação na Google Play', appFeatures:['Vários cartões, categorias e tags','Parcelas, gastos fixos e limites','Importação de planilhas Itaú e relatórios em PDF','Notificações opcionais com revisão na Central de diagnóstico','Dashboard, lembretes e backup protegido por senha'], appLink:'Conheça o Fatura na Risca', appPrivacy:'Seus dados ficam no aparelho. Sem anúncios e sem envio dos dados financeiros a servidores.', appDetail:'Com sua autorização, notificações de fontes financeiras conhecidas entram na Central de diagnóstico. Confira e salve uma cobrança para ensinar um padrão local; ocorrências compatíveis passam a ser registradas automaticamente. Você também pode rejeitar padrões e cadastrar despesas manualmente.', appPrice:'Preço planejado: R$ 10,00 · compra única', appNote:'A disponibilidade e o preço final serão informados na Google Play. A identificação de notificações depende do formato enviado pelo banco ou carteira e não substitui a fatura oficial.',
    coursesKicker:'Aprendizado prático', coursesTitle:'Sua próxima etapa<br>começa nos fundamentos.', coursesIntro:'Materiais digitais para aprender banco de dados, SQL e PL/SQL, com explicações objetivas e prática na ordem certa.', coursesHeading:'Cursos e e-books', coursesDescription:'Uma trilha de aprendizado que conecta fundamentos, consultas SQL e programação com Oracle.', details:'Conhecer o material', bookLabel:'E-BOOK', back:'Voltar para cursos e e-books', contentTitle:'O que você vai estudar', whoTitle:'Aprenda com clareza, pratique com propósito.', whoText:'Estude no seu ritmo, siga a sequência dos assuntos e volte aos exemplos sempre que precisar. O foco é compreender a lógica e aplicar os conceitos.', askMaterial:'Consultar acesso ao material', offerNote:'Valores de referência da apresentação atual. Consulte por e-mail as condições e o link de compra antes de adquirir.', sqlIncluded:['E-book em português e inglês','5 scripts SQL prontos para executar','Exercícios com respostas comentadas','Checklist de referência rápida'],
    books:{
      databases:{title:'Banco de Dados do Zero', short:'Fundamentos, tabelas, chaves e uma base para começar na área de dados.', intro:'Entenda os conceitos por trás de um banco de dados antes de avançar para os comandos. Um ponto de partida para conectar as peças e estudar com mais confiança.', price:'US$ 9', model:'Complemento no checkout da oferta SQL', subjects:['Conceitos fundamentais de banco de dados','Tabelas, relacionamentos e chaves','Introdução ao ecossistema Oracle','Caminhos profissionais na área de dados'], code:'FUNDAMENTOS'},
      sql:{title:'SQL com Oracle para Iniciantes', short:'Consultas, filtros, funções, JOINs e agrupamentos com prática guiada.', intro:'Comece do zero e avance por consultas, filtros, funções, JOINs e agrupamentos. Explicações diretas e scripts prontos ajudam a transformar conceitos em prática.', price:'US$ 37', model:'Oferta principal · material digital', subjects:['Ambiente e dados de estudo','SELECT, aliases, WHERE e ordenação','Funções de texto, números e datas','Relacionamentos entre tabelas com JOIN','GROUP BY e funções de agregação'], code:'SELECT / JOIN'},
      plsql:{title:'PL/SQL do Zero', short:'Da estrutura de um bloco à programação de rotinas no Oracle.', intro:'Evolua das consultas para a programação no banco de dados. Conheça a estrutura de blocos e as ferramentas para escrever rotinas com PL/SQL.', price:'US$ 47', model:'Próxima etapa da trilha · oferta após a compra', subjects:['Blocos, variáveis e estruturas de controle','Loops e cursores','Procedures e functions','Packages','Triggers'], code:'BEGIN / END'}
    },
    bundleTitle:'Trilha Prática de Banco de Dados', bundleIntro:'Os três e-books na sequência certa: fundamentos, SQL com Oracle e PL/SQL. Uma visão integrada para construir sua base e avançar.', bundleButton:'Conhecer a trilha completa', bundleLabel:'PACOTE COMPLETO', bundleIncluded:['Banco de Dados do Zero','SQL com Oracle para Iniciantes','PL/SQL do Zero','Scripts, exercícios, gabaritos e checklists'], materialDisclaimer:'Material independente, sem promessa de emprego, certificação ou resultado financeiro. Oracle é marca registrada da Oracle Corporation. Este material não é afiliado, endossado ou patrocinado pela Oracle.',
    contactTitle:'Uma boa solução começa<br>com uma conversa.', contactIntro:'Conte sua necessidade, fale sobre um projeto ou tire dúvidas sobre nossos materiais e o Fatura na Risca.', contactPage:'Vamos conversar?', contactPageIntro:'Entre em contato para falar sobre consultoria, soluções digitais, materiais de estudo ou suporte ao aplicativo.', send:'Enviar e-mail', responsible:'Responsável', company:'Empresa', direct:'Contato direto', contactNote:'O botão abre seu aplicativo de e-mail. Nenhuma mensagem é enviada automaticamente.', subject:'Contato pelo site Tee How', materialSubject:'Informações sobre ', footer:'Consultoria, soluções digitais e aprendizado prático.', privacy:'Privacidade do app', terms:'Termos do app', support:'Suporte ao app', local:'Português e inglês · Mesma experiência', rights:'Todos os direitos reservados.', pageDescription:'Consultoria em tecnologia, soluções digitais e aprendizado prático em bancos de dados.'
  },
  en: {
    locale:'en', suffix:'Technology Consulting', skip:'Skip to content', menu:'Menu', close:'Close menu', change:'Mudar para português', nav:['Home','Services','Courses and e-books','Fatura na Risca','Contact'],
    title:'Technology with purpose.', eyebrow:'Tee How · Technology Consulting', hero:'Clear ideas.<br>Solutions <em>that make sense.</em>', intro:'Consulting, digital solutions and hands-on learning. We turn real needs into useful tools with clarity, organization and attention to the people who use them.',
    talk:'Let’s talk', explore:'Explore our work', sideLabel:'CLARITY / PRACTICE / PROGRESS', side:'From a real problem<br>to a <strong>digital solution.</strong>', topics:['Consulting','Applications','Automation','Databases'],
    servicesKicker:'Database consulting', servicesTitle:'Well-managed data.<br>More efficient operations.', servicesIntro:'From query performance to data organization: solutions to make your environment more reliable, efficient and ready to evolve.', servicesPage:'Database services', servicesMore:'Explore all service areas', processTitle:'How we work', processIntro:'The scope is defined around your environment, business priorities and the risks of each change.', processSteps:[['Assessment','We understand the environment, identify bottlenecks and align priorities.'],['Action plan','We define the scope, recommendations and validation criteria before execution.'],['Implementation and validation','We implement the agreed changes, check the results and document the deliverables.']],
    services:[
      ['Performance and tuning','Bottleneck identification and query and routine optimization to make better use of your environment’s resources.',['Query and execution plan analysis','Index and statistics review','Slow query, blocking and resource usage diagnosis']],
      ['Database administration','Organized operations and maintenance routines focused on stability, security and continuity.',['Configuration, maintenance and monitoring','Access and privilege review','Backup planning and recovery testing']],
      ['Data modeling and architecture','Data structures aligned with business rules, designed for consistency and future growth.',['Logical and physical data modeling','Table, key and relationship review','Integrity, standardization and documentation']],
      ['SQL and PL/SQL development','Well-organized database queries and routines to support applications and business processes.',['SQL queries and business rules','Procedures, functions and packages','Code review and routine automation']],
      ['Integration, migration and quality','Support for moving and integrating data, with checks to preserve information consistency.',['Data mapping and transformation','Data load and migration planning','Reconciliation, duplicate handling and validation']],
      ['Data analysis and reporting','Information preparation to make indicators easier to interpret and support decisions with consistent data.',['Queries and datasets for reports','Indicator definition and validation','Data organization for dashboards and analysis']]
    ],
    productKicker:'Our application', productTitle:'Fewer surprises.<br>More control.', appTagline:'Your cards under control', appIntro:'Fatura na Risca brings together tools to track purchases, organize credit card statements and plan the coming months on Android.', appStatus:'Being prepared for release on Google Play', appFeatures:['Multiple cards, categories and tags','Installments, recurring expenses and limits','Itaú spreadsheet imports and PDF reports','Optional notifications reviewed in the diagnostic center','Dashboard, reminders and password-protected backups'], appLink:'Explore Fatura na Risca', appPrivacy:'Your data stays on your device. No ads and no financial data sent to servers.', appDetail:'With your permission, notifications from recognized financial apps go to the diagnostic center. Review and save a purchase to teach a local pattern; matching notifications can then be recorded automatically. You can also reject patterns and enter expenses manually.', appPrice:'Planned price: R$ 10.00 · one-time purchase', appNote:'Availability and final pricing will be shown on Google Play. Notification detection depends on the format sent by the bank or wallet and does not replace the official statement.',
    coursesKicker:'Hands-on learning', coursesTitle:'Your next step<br>starts with the foundations.', coursesIntro:'Digital materials for learning databases, SQL and PL/SQL, with straightforward explanations and practice in the right order.', coursesHeading:'Courses and e-books', coursesDescription:'A learning path connecting database foundations, SQL queries and Oracle programming.', details:'Explore the material', bookLabel:'E-BOOK', back:'Back to courses and e-books', contentTitle:'What you will study', whoTitle:'Learn with clarity. Practice with purpose.', whoText:'Study at your own pace, follow the topics in order and revisit examples whenever you need. The focus is on understanding the logic and applying the concepts.', askMaterial:'Ask about access to the material', offerNote:'Reference prices from the current presentation. Contact us by email to confirm purchase terms and the checkout link before buying.', sqlIncluded:['E-book in Portuguese and English','5 ready-to-run SQL scripts','Exercises with commented answers','Quick-reference checklist'],
    books:{
      databases:{title:'Databases from Zero', short:'Foundations, tables, keys and a starting point for learning about data.', intro:'Understand the concepts behind a database before moving on to commands. A starting point to connect the pieces and study with greater confidence.', price:'US$ 9', model:'Checkout add-on to the SQL offer', subjects:['Fundamental database concepts','Tables, relationships and keys','Introduction to the Oracle ecosystem','Career paths in data'], code:'FOUNDATIONS'},
      sql:{title:'SQL with Oracle for Beginners', short:'Queries, filters, functions, JOINs and grouping with guided practice.', intro:'Start from scratch and progress through queries, filters, functions, JOINs and grouping. Clear explanations and ready-to-run scripts help turn concepts into practice.', price:'US$ 37', model:'Main offer · digital material', subjects:['Study environment and sample data','SELECT, aliases, WHERE and sorting','Text, numeric and date functions','Connecting tables with JOIN','GROUP BY and aggregate functions'], code:'SELECT / JOIN'},
      plsql:{title:'PL/SQL from Zero', short:'From the structure of a block to programming routines in Oracle.', intro:'Move from queries to database programming. Learn block structure and the tools for writing PL/SQL routines.', price:'US$ 47', model:'Next step in the path · post-purchase offer', subjects:['Blocks, variables and control structures','Loops and cursors','Procedures and functions','Packages','Triggers'], code:'BEGIN / END'}
    },
    bundleTitle:'Database Practice Starter Path', bundleIntro:'All three e-books in the right sequence: foundations, SQL with Oracle and PL/SQL. An integrated approach to building your knowledge and moving forward.', bundleButton:'Explore the complete path', bundleLabel:'COMPLETE BUNDLE', bundleIncluded:['Databases from Zero','SQL with Oracle for Beginners','PL/SQL from Zero','Scripts, exercises, answer keys and checklists'], materialDisclaimer:'Independent material with no promise of employment, certification or financial results. Oracle is a registered trademark of Oracle Corporation. This material is not affiliated with, endorsed by or sponsored by Oracle.',
    contactTitle:'A good solution starts<br>with a conversation.', contactIntro:'Tell us what you need, discuss a project or ask about our materials and Fatura na Risca.', contactPage:'Let’s talk?', contactPageIntro:'Get in touch about consulting, digital solutions, learning materials or application support.', send:'Send an email', responsible:'Contact person', company:'Company', direct:'Direct contact', contactNote:'The button opens your email application. No message is sent automatically.', subject:'Contact from the Tee How website', materialSubject:'Information about ', footer:'Consulting, digital solutions and hands-on learning.', privacy:'App privacy policy', terms:'App terms of use', support:'App support', local:'Portuguese and English · The same experience', rights:'All rights reserved.', pageDescription:'Technology consulting, digital solutions and hands-on database learning.'
  }
};
function escapeText(value) { return String(value).replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character])); }
function preferredLanguage() { try { return localStorage.getItem('teehow-language') === 'en' ? 'en' : 'pt'; } catch { return 'pt'; } }
function route() {
  const [language, page] = location.hash.replace(/^#\/?/, '').split('/');
  const selectedPage = ['databases','sql','plsql','bundle'].includes(page) ? 'courses' : page;
  return {language: language === 'en' ? 'en' : language === 'pt' ? 'pt' : preferredLanguage(), page: pages.includes(selectedPage) ? selectedPage : 'home'};
}
let state = route();
function link(page) { return '#/' + state.language + '/' + page; }
function email(subject) { return 'mailto:' + EMAIL + '?subject=' + encodeURIComponent(subject); }
function button(label, href, style='primary') { return '<a class="button ' + style + '" href="' + escapeText(href) + '">' + escapeText(label) + '</a>'; }
function brand(c) { return '<a class="brand" href="' + link('home') + '" aria-label="Tee How"><img class="brand-logo" src="assets/teehow-logo-web-v2.png" width="48" height="48" alt=""><span><span class="brand-name">Tee How</span><span class="brand-sub">' + c.suffix + '</span></span></a>'; }
function list(items) { return '<ul class="feature-list">' + items.map(item=>'<li>' + escapeText(item) + '</li>').join('') + '</ul>'; }
function contactBand(c) { return '<section class="contact-band"><div class="wrap contact-grid"><div><h2>' + c.contactTitle + '</h2><p>' + c.contactIntro + '</p></div>' + button(c.talk,link('contact')) + '</div></section>'; }
function serviceCards(c, detailed=false) {
  return '<div class="service-grid">' + (detailed ? c.services : c.services.slice(0,3)).map(([title,body,items],i)=>'<article class="service-card"><div class="number">0' + (i+1) + '<span aria-hidden="true">+</span></div><h3>' + title + '</h3><p>' + body + '</p>' + (detailed ? list(items) : '') + '</article>').join('') + '</div>' + (detailed ? '' : '<p>' + button(c.servicesMore,link('services'),'secondary') + '</p>');
}
function resourceCards(c) {
  const english = state.language === 'en';
  return '<div class="product-panel"><span class="kicker">' + (english ? 'Coming soon' : 'Em breve') + '</span><h2>' + (english ? 'Under construction' : 'Em construção') + '</h2><p>' + (english ? 'We are preparing this section. Courses and e-books are not available for purchase at this time.' : 'Estamos preparando esta seção. Os cursos e e-books não estão disponíveis para compra neste momento.') + '</p></div>';
}
function appPanel(c) { return '<div class="product-panel"><div class="app-brand"><img src="assets/fatura-na-risca.png" alt="" width="72" height="72"><div><h3>Fatura na Risca</h3><p>' + c.appTagline + '</p></div></div>' + list(c.appFeatures) + '<span class="pill">' + c.appStatus + '</span></div>'; }
function pageHead(title, description, c, back=false) { return '<section class="page-head"><div class="wrap">' + (back?'<a class="back" href="' + link('courses') + '">' + c.back + '</a>':'') + '<span class="kicker">Tee How / ' + c.suffix + '</span><h1>' + title + '</h1><p>' + description + '</p></div></section>'; }
function legal(c) { return '<div class="legal-links"><a class="text-link" href="' + POLICY + 'privacy.html">' + c.privacy + '</a><a class="text-link" href="' + POLICY + 'terms.html">' + c.terms + '</a><a class="text-link" href="' + POLICY + 'support.html">' + c.support + '</a></div>'; }
function home(c) {
  return '<section class="hero"><div class="wrap hero-grid"><div><div class="eyebrow">' + c.eyebrow + '</div><h1>' + c.hero + '</h1><p class="lead">' + c.intro + '</p><div class="actions">' + button(c.talk,link('contact')) + button(c.explore,link('services'),'outline') + '</div></div><div class="hero-side"><div class="hero-side-top"><span>' + c.sideLabel + '</span><span aria-hidden="true">/ TH</span></div><div class="hero-statement">' + c.side + '</div><div class="hero-topics">' + c.topics.map((topic,i)=>'<div class="topic"><b>0' + (i+1) + '</b>' + topic + '</div>').join('') + '</div></div></div></section>' +
    '<section class="section gray"><div class="wrap"><div class="section-heading"><div><span class="kicker">' + c.servicesKicker + '</span><h2>' + c.servicesTitle + '</h2></div><p>' + c.servicesIntro + '</p></div>' + serviceCards(c) + '</div></section>' +
    '<section class="section"><div class="wrap product-grid"><div class="product-copy"><span class="kicker">' + c.productKicker + '</span><h2>' + c.productTitle + '</h2><p>' + c.appIntro + '</p><a class="text-link" href="' + link('app') + '">' + c.appLink + '</a></div>' + appPanel(c) + '</div></section>' +
    '<section class="section gray"><div class="wrap"><div class="section-heading"><div><span class="kicker">' + c.coursesKicker + '</span><h2>' + c.coursesHeading + '</h2></div></div>' + resourceCards(c) + '</div></section>' + contactBand(c);
}
function courseDetail(key,c) {
  const isBundle=key==='bundle', book=isBundle?{title:c.bundleTitle,intro:c.bundleIntro,price:'US$ 67',model:c.bundleLabel,subjects:c.bundleIncluded}:c.books[key];
  return pageHead(book.title,book.intro,c,true) + '<section class="section"><div class="wrap detail-grid"><div><span class="kicker">' + c.coursesKicker + '</span><h2>' + c.contentTitle + '</h2>' + list(book.subjects) + (key==='sql'?list(c.sqlIncluded):'') + '<h3>' + c.whoTitle + '</h3><p>' + c.whoText + '</p>' + (isBundle?'<div class="actions">' + ['databases','sql','plsql'].map(k=>button(c.books[k].title,link(k),'secondary')).join('') + '</div>':'') + '</div><aside class="detail-box"><span class="kicker">' + book.model + '</span><h3>' + book.title + '</h3><div class="price">' + book.price + '</div>' + button(c.askMaterial,email(c.materialSubject+book.title)) + '<p class="notice">' + c.offerNote + '</p></aside></div><div class="wrap"><p class="notice">' + c.materialDisclaimer + '</p></div></section>' + contactBand(c);
}
function content(page,c) {
  if (page==='home') return home(c);
  if (page==='services') return pageHead(c.servicesPage,c.servicesIntro,c) + '<section class="section"><div class="wrap">' + serviceCards(c,true) + '</div></section><section class="section gray"><div class="wrap"><div class="section-heading"><h2>' + c.processTitle + '</h2><p>' + c.processIntro + '</p></div><div class="service-grid">' + c.processSteps.map(([title,body],i)=>'<article class="service-card"><span class="kicker">0' + (i+1) + '</span><h3>' + title + '</h3><p>' + body + '</p></article>').join('') + '</div></div></section>' + contactBand(c);
  if (page==='courses') return pageHead(c.coursesHeading,state.language==='en'?'New learning materials are being prepared.':'Novos materiais de aprendizado estão sendo preparados.',c) + '<section class="section gray"><div class="wrap">' + resourceCards(c) + '</div></section>' + contactBand(c);
  if (page==='app') return pageHead('Fatura na Risca',c.appTagline,c) + '<section class="section"><div class="wrap product-grid"><div class="product-copy"><span class="kicker">Android / ' + c.productKicker + '</span><h2>' + c.productTitle + '</h2><p>' + c.appIntro + '</p><p>' + c.appDetail + '</p><p><strong>' + c.appPrivacy + '</strong></p><p>' + c.appPrice + '</p><p class="notice">' + c.appNote + '</p>' + legal(c) + '</div>' + appPanel(c) + '</div></section>' + contactBand(c);
  if (page==='contact') return pageHead(c.contactPage,c.contactPageIntro,c) + '<section class="section"><div class="wrap detail-grid"><div><span class="kicker">' + c.direct + '</span><h2>' + c.contactTitle + '</h2><p>' + c.contactIntro + '</p>' + button(c.send,email(c.subject)) + '<p class="notice">' + c.contactNote + '</p></div><div class="contact-card"><h3>Tee How</h3><dl><dt>' + c.company + '</dt><dd>Tee How Consultoria em Tecnologia</dd><dt>' + c.responsible + '</dt><dd>Vitor Tee How Siao Junior</dd><dt>E-mail</dt><dd><a class="text-link" href="' + email(c.subject) + '">' + EMAIL + '</a></dd></dl></div></div></section>';
  return courseDetail(page,c);
}
function render() {
  state=route(); const c=copy[state.language]; document.documentElement.lang=c.locale;
  const active=pages.indexOf(state.page)>4?'courses':state.page;
  document.querySelector('.skip-link').textContent=c.skip;
  document.getElementById('header').innerHTML='<div class="wrap header-inner">' + brand(c) + '<nav class="nav" id="nav" aria-label="' + (state.language==='pt'?'Navegação principal':'Main navigation') + '">' + ['home','services','courses','app','contact'].map((p,i)=>'<a href="' + link(p) + '"' + (active===p?' aria-current="page"':'') + '>' + c.nav[i] + '</a>').join('') + '</nav><div class="header-actions"><button class="menu-button" aria-expanded="false" aria-controls="nav">' + c.menu + '</button><button class="lang-button" aria-label="' + c.change + '" lang="' + (state.language==='pt'?'en':'pt-BR') + '"><span aria-hidden="true">◎</span>' + (state.language==='pt'?'English':'Português') + '</button></div></div>';
  document.getElementById('main').innerHTML=content(state.page,c);
  document.getElementById('footer').innerHTML='<div class="wrap"><div class="footer-top"><div>' + brand(c) + '<p>' + c.footer + '</p></div><div class="footer-links"><a href="' + link('courses') + '">' + c.nav[2] + '</a><a href="' + POLICY + 'privacy.html">' + c.privacy + '</a><a href="' + POLICY + 'terms.html">' + c.terms + '</a><a href="' + link('contact') + '">' + c.nav[4] + '</a></div></div><div class="footer-bottom"><span>© ' + new Date().getFullYear() + ' Tee How Consultoria em Tecnologia. ' + c.rights + '</span><span>' + c.local + '</span></div></div>';
  const pageTitle=state.page==='home'?c.title:state.page==='bundle'?c.bundleTitle:(c.books[state.page]?.title ?? c.nav[pages.indexOf(state.page)]);
  document.title=pageTitle+' | Tee How';
  document.querySelector('meta[name="description"]').content=c.pageDescription;
  document.querySelector('.lang-button').addEventListener('click',()=>{const next=state.language==='pt'?'en':'pt';try{localStorage.setItem('teehow-language',next);}catch{}location.hash='#/'+next+'/'+state.page;});
  document.querySelector('.menu-button').addEventListener('click',event=>{const opened=document.getElementById('nav').classList.toggle('open');event.currentTarget.setAttribute('aria-expanded',String(opened));event.currentTarget.textContent=opened?c.close:c.menu;});
}
document.querySelector('.skip-link').addEventListener('click',event=>{event.preventDefault();document.getElementById('main').focus();document.getElementById('main').scrollIntoView();});
document.getElementById('header').addEventListener('keydown',event=>{if(event.key==='Escape'){document.getElementById('nav').classList.remove('open');const btn=document.querySelector('.menu-button');btn.setAttribute('aria-expanded','false');btn.textContent=copy[state.language].menu;}});
window.addEventListener('hashchange',()=>{const previous=state;render();if(previous.page!==state.page){window.scrollTo(0,0);document.getElementById('main').focus({preventScroll:true});}});
render();
