'use strict';
const foundationCopy = {
  pt: {
    label:'Primeiro e-book · Nível iniciante', title:'Database Foundations', subtitle:"A Practical Beginner’s Guide", tagline:'Entenda os fundamentos.<br>Comece a praticar <em>SQL.</em>',
    intro:'Conecte tabelas, chaves, relacionamentos e consultas em um caminho de estudo prático. Um guia para quem quer entender banco de dados antes de avançar para assuntos mais complexos.',
    summary:"Aprenda os fundamentos de banco de dados, pratique SQL e dê os primeiros passos no Oracle. Um guia para iniciantes, com exemplos, exercícios e um miniprojeto para aplicar o que aprendeu.",
    view:'Conhecer o e-book', validation:"Ver na Payhip", validationNote:'Você será encaminhado à loja na Payhip para consultar preço, disponibilidade e condições de compra.',
    format:'E-book em PDF', language:'Conteúdo em inglês', level:'Sem experiência profissional prévia', coverAlt:'Capa do e-book Database Foundations: A Practical Beginner’s Guide, de Vitor Tee How Siao Júnior',
    stats:[['34','páginas'],['25','seções'],['10','exercícios'],['30','dias no plano de estudo']],
    previewLabel:'Capa da edição 1.0', learnTitle:'Uma base que conecta as peças.', learnIntro:'Da estrutura de uma tabela à primeira consulta com JOIN. A sequência acompanha o conteúdo do guia, sem pular os fundamentos.',
    modules:[
      ['Fundamentos relacionais','Bancos de dados, tabelas, linhas, colunas, tipos de dados, NULL e o papel dos relacionamentos.'],
      ['Chaves e integridade','Chaves primárias, chaves estrangeiras e a relação entre clientes e pedidos.'],
      ['Seus primeiros comandos SQL','SELECT, WHERE, ORDER BY e os cuidados ao usar INSERT, UPDATE e DELETE.'],
      ['Consultas que conectam informações','COUNT, SUM, AVG, MIN, MAX, GROUP BY, HAVING, JOIN e LEFT JOIN.'],
      ['Oracle, PL/SQL e a área de dados','Diferenças entre SQL, Oracle Database e PL/SQL, a atuação de um DBA e caminhos para continuar estudando.'],
      ['Prática e revisão','Miniprojeto, exercícios, respostas comentadas, plano de estudo, checklist e glossário.']
    ],
    projectKicker:'Do conceito à prática', projectTitle:'Uma loja virtual.<br>Quatro tabelas.<br>Perguntas reais.', projectIntro:'O miniprojeto usa clientes, produtos, pedidos e itens de pedidos para conectar modelagem e consultas em um cenário didático.', projectTasks:['Relacionar cada pedido ao seu cliente','Calcular o valor total de um pedido','Encontrar clientes sem pedidos','Analisar produtos e categorias'],
    projectNote:'Exemplos para estudo: pratique em ambiente de testes, nunca diretamente em dados de produção.',
    includedTitle:'Tudo dentro do próprio guia.', included:['Exemplos SQL ao longo dos capítulos','Miniprojeto com estrutura das tabelas e dados de exemplo','10 exercícios e gabarito comentado','Plano de estudo de 30 dias','Checklist de fundamentos e glossário'],
    audienceTitle:'Para quem está dando os primeiros passos.', audience:'Estudantes de tecnologia, analistas de suporte, desenvolvedores iniciantes e pessoas explorando a área de dados. O guia não exige experiência profissional prévia em banco de dados.',
    authorTitle:'Aprenda com quem vive o dia a dia dos dados.', authorIntro:'Vitor Tee How Siao Júnior', authorText:'Autor do guia e responsável pela Tee How Consultoria em Banco de Dados. No e-book, apresenta sua trajetória de mais de duas décadas com sistemas e bancos de dados em ambientes corporativos, incluindo administração, desenvolvimento, migração e tuning.',
    faqTitle:'Antes de começar', faq:[['O material está em português?','Esta edição do PDF está em inglês. A página de apresentação está disponível em português e inglês; isso não significa que o e-book foi traduzido.'],['É um curso em vídeo?','Não. É um e-book em PDF para estudo no seu ritmo, com exemplos, exercícios e um miniprojeto. Não inclui videoaulas.'],['Preciso conhecer SQL?','Não é necessário ter experiência profissional prévia. O guia começa com conceitos básicos e avança gradualmente para as consultas.'],['O plano garante aprendizado em 30 dias?','Não. O plano de 30 dias é uma sugestão de organização do estudo, não uma garantia de domínio do assunto ou de resultado profissional.'],['Já posso comprar?','Acesse a loja na Payhip pelo botão desta página para consultar preço, disponibilidade e condições de compra.'],['Inclui certificação?','Não é um curso de certificação e não promete emprego ou renda. É um material educacional independente.']],
    closing:'Seu primeiro passo começa<br>com uma base sólida.', closingIntro:'Conheça a proposta do guia e consulte as condições de compra na loja da Payhip.', contact:'Tirar uma dúvida', disclaimer:'Material educacional independente. Oracle é marca registrada da Oracle Corporation. O guia não é afiliado, patrocinado ou endossado pela Oracle. Sem promessa de certificação, emprego ou renda.', other:"Novos materiais para continuar aprendendo estão em desenvolvimento.", meta:'Conheça Database Foundations: e-book em inglês com 34 páginas, SQL para iniciantes, miniprojeto, exercícios comentados e plano de estudo. Consulte na Payhip.'
  },
  en: {
    label:'First e-book · Beginner level', title:'Database Foundations', subtitle:"A Practical Beginner’s Guide", tagline:'Understand the foundations.<br>Start practicing <em>SQL.</em>',
    intro:'Connect tables, keys, relationships and queries through a practical study path. A guide for understanding databases before moving on to more complex topics.',
    summary:"Learn database foundations, practice SQL and take your first steps with Oracle. A beginner’s guide with examples, exercises and a mini project to apply what you have learned.",
    view:'Explore the e-book', validation:"View on Payhip", validationNote:'You will be redirected to the Payhip store to check pricing, availability and purchase terms.',
    format:'PDF e-book', language:'Content in English', level:'No prior professional experience required', coverAlt:'Cover of Database Foundations: A Practical Beginner’s Guide, by Vitor Tee How Siao Júnior',
    stats:[['34','pages'],['25','sections'],['10','exercises'],['30','days in the study plan']],
    previewLabel:'Version 1.0 cover', learnTitle:'Build a foundation that connects the pieces.', learnIntro:'From the structure of a table to your first JOIN query. The sequence follows the guide without skipping the fundamentals.',
    modules:[
      ['Relational foundations','Databases, tables, rows, columns, data types, NULL and the role of relationships.'],
      ['Keys and integrity','Primary keys, foreign keys and the relationship between customers and orders.'],
      ['Your first SQL commands','SELECT, WHERE, ORDER BY and precautions when using INSERT, UPDATE and DELETE.'],
      ['Queries that connect information','COUNT, SUM, AVG, MIN, MAX, GROUP BY, HAVING, JOIN and LEFT JOIN.'],
      ['Oracle, PL/SQL and the data field','The differences between SQL, Oracle Database and PL/SQL, a DBA’s role and directions for further study.'],
      ['Practice and review','Mini project, exercises, commented answers, study plan, checklist and glossary.']
    ],
    projectKicker:'From concepts to practice', projectTitle:'One online store.<br>Four tables.<br>Real questions.', projectIntro:'The mini project uses customers, products, orders and order items to connect modeling and queries in an educational scenario.', projectTasks:['Connect each order to its customer','Calculate the total value of an order','Find customers without orders','Analyze products and categories'],
    projectNote:'Educational examples: practice in a test environment, never directly against production data.',
    includedTitle:'All within the guide itself.', included:['SQL examples throughout the chapters','Mini project with table definitions and sample data','10 exercises and a commented answer key','30-day study plan','Foundations checklist and glossary'],
    audienceTitle:'For those taking their first steps.', audience:'Technology students, support analysts, junior developers and people exploring the data field. No prior professional database experience is required.',
    authorTitle:'Learn from everyday work with data.', authorIntro:'Vitor Tee How Siao Júnior', authorText:'Author of the guide and founder of Tee How Consultoria em Banco de Dados. In the e-book, he describes more than two decades of working with systems and databases in corporate environments, including administration, development, migration and tuning.',
    faqTitle:'Before you start', faq:[['Is the material in Portuguese?','This PDF edition is in English. The presentation page is available in Portuguese and English; this does not mean the e-book has been translated.'],['Is this a video course?','No. It is a PDF e-book for self-paced study, with examples, exercises and a mini project. Video lessons are not included.'],['Do I need to know SQL?','No prior professional experience is required. The guide starts with basic concepts and gradually moves on to queries.'],['Does the plan guarantee learning in 30 days?','No. The 30-day plan is a suggested study schedule, not a guarantee of mastery or professional results.'],['Can I purchase it now?','Use the button on this page to visit the Payhip store and check pricing, availability and purchase terms.'],['Does it include certification?','It is not a certification course and does not promise employment or income. It is independent educational material.']],
    closing:'Your first step starts<br>with a solid foundation.', closingIntro:'Explore what the guide offers and check purchase terms in the Payhip store.', contact:'Ask a question', disclaimer:'Independent educational material. Oracle is a registered trademark of Oracle Corporation. The guide is not affiliated with, sponsored by or endorsed by Oracle. No promise of certification, employment or income.', other:"New materials to continue your learning are in development.", meta:'Explore Database Foundations: a 34-page English e-book with beginner SQL, a mini project, commented exercises and a study plan. View on Payhip.'
  }
};
function foundationStatus(f) { return '<a class="button primary" href="' + escapeText(f.purchaseUrl || 'https://payhip.com/TeeHowDatabaseConsulting') + '" target="_blank" rel="noopener noreferrer">' + escapeText(f.validation) + ' ↗</a><p class="notice">' + escapeText(f.validationNote) + '</p>'; }
function ebookCatalogCard(f,page) {
  return '<article class="ebook-feature"><div class="ebook-thumb"><img src="' + escapeText(f.cover || 'assets/database-foundations-cover.png') + '" alt="' + escapeText(f.coverAlt) + '" width="773" height="1000" loading="lazy"></div><div><span class="kicker">' + f.label + '</span><h2>' + f.title + '</h2><p class="ebook-subtitle">' + f.subtitle + '</p><p>' + f.summary + '</p><div class="ebook-tags"><span>' + f.format + '</span><span>' + f.language + '</span></div><div class="actions">' + button(f.view,link(page)) + '</div><p class="notice"><span class="pill">' + f.validation + '</span></p></div></article>';
}
function foundationCatalog(c) {
  return '<div class="ebook-catalog">' + ebookCatalogCard(foundationCopy[state.language],'databases') + ebookCatalogCard(advancedCopy[state.language],'advanced-sql') + '</div><p class="notice">' + foundationCopy[state.language].other + '</p>';
}
function ebookProject(f) {
  if(f.projectStages) return '<div class="ebook-project">' + f.projectStages.map(([title,text])=>'<div class="schema-table"><b>' + escapeText(title) + '</b><p>' + escapeText(text) + '</p></div>').join('<span aria-hidden="true">↓</span>') + '</div>';
  return '<div class="ebook-project" aria-label="CUSTOMERS, ORDERS, ORDER_ITEMS, PRODUCTS"><div class="schema-table"><b>CUSTOMERS</b><code>customer_id · name · city</code></div><span aria-hidden="true">↓</span><div class="schema-table"><b>ORDERS</b><code>order_id · customer_id · order_date</code></div><span aria-hidden="true">↓</span><div class="schema-table"><b>ORDER_ITEMS</b><code>order_id · product_id · quantity</code></div><span aria-hidden="true">↑</span><div class="schema-table"><b>PRODUCTS</b><code>product_id · product_name · price</code></div></div>';
}
function foundationLanding(c) { return ebookLanding(foundationCopy[state.language],c); }
function ebookLanding(f,c) {
  return '<section class="hero ebook-hero"><div class="wrap"><a class="back" href="' + link('courses') + '">' + c.back + '</a><div class="hero-grid"><div><div class="eyebrow">' + f.label + '</div><p class="ebook-name">' + f.title + ' <span>' + f.subtitle + '</span></p><h1>' + f.tagline + '</h1><p class="lead">' + f.intro + '</p><div class="ebook-tags"><span>' + f.format + '</span><span>' + f.language + '</span></div>' + foundationStatus(f) + '</div><figure class="ebook-cover"><img src="' + escapeText(f.cover || 'assets/database-foundations-cover.png') + '" alt="' + escapeText(f.coverAlt) + '" width="773" height="1000" fetchpriority="high"><figcaption>' + f.previewLabel + '</figcaption></figure></div></div></section>' +
    '<section class="ebook-stats" aria-label="' + f.title + '"><div class="wrap">' + f.stats.map(([value,label])=>'<div><strong>' + value + '</strong><span>' + label + '</span></div>').join('') + '</div></section>' +
    '<section class="section"><div class="wrap"><div class="section-heading"><h2>' + f.learnTitle + '</h2><p>' + f.learnIntro + '</p></div><div class="service-grid">' + f.modules.map(([title,text],i)=>'<article class="service-card"><span class="kicker">0' + (i+1) + '</span><h3>' + title + '</h3><p>' + text + '</p></article>').join('') + '</div></div></section>' +
    '<section class="section gray"><div class="wrap product-grid"><div><span class="kicker">' + f.projectKicker + '</span><h2>' + f.projectTitle + '</h2><p>' + f.projectIntro + '</p>' + list(f.projectTasks) + '<p class="notice">' + f.projectNote + '</p></div>' + ebookProject(f) + '</div></section>' +
    '<section class="section"><div class="wrap detail-grid"><div><h2>' + f.includedTitle + '</h2>' + list(f.included) + '</div><aside class="detail-box"><h3>' + f.audienceTitle + '</h3><p>' + f.audience + '</p><span class="pill">' + f.level + '</span></aside></div></section>' +
    '<section class="section gray"><div class="wrap detail-grid"><div><span class="kicker">Tee How</span><h2>' + f.authorTitle + '</h2></div><div><h3>' + f.authorIntro + '</h3><p>' + f.authorText + '</p></div></div></section>' +
    '<section class="section"><div class="wrap ebook-faq"><h2>' + f.faqTitle + '</h2>' + f.faq.map(([question,answer])=>'<details><summary>' + question + '</summary><p>' + answer + '</p></details>').join('') + '</div></section>' +
    '<section class="contact-band"><div class="wrap contact-grid"><div><h2>' + f.closing + '</h2><p>' + f.closingIntro + '</p></div><div>' + foundationStatus(f) + button(f.contact,email(c.materialSubject+f.title),'secondary') + '</div></div></section><div class="wrap"><p class="notice ebook-disclaimer">' + f.disclaimer + '</p></div>';
}
